minerals/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'(?P<pk>\d+)/$', views.mineral_detail, name='detail'),

]

minerals_catalog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


from . import views

urlpatterns = [
    url(r'search/$', views.mineral_search, name='search'),
    url(r'group/(?P<group>[a-zA-Z\s]{2,})/$', views.mineral_group, name='group'),
    url(r'letter/(?P<letter>[a-zA-Z])/$', views.mineral_letter, name='letter'),
    url(r'color/(?P<color>[a-zA-Z]+)/$', views.mineral_color, name='color'),
    url(r'^minerals/', include('minerals.urls', namespace='minerals')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns =[
         url(r'^__debug__/', include(debug_toolbar.urls)),
         ] + urlpatterns

minerals/models.py
from django.db import models
import json


class Mineral(models.Model):
    """Mineral class model to create minerals"""
    name = models.CharField(max_length=100, unique=True)
    image_filename = models.CharField(max_length=255)
    image_caption = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    strunz_classification = models.CharField(max_length=255)
    crystal_system = models.CharField(max_length=255)
    unit_cell = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    crystal_symmetry = models.CharField(max_length=255)
    cleavage = models.CharField(max_length=255)
    mohs_scale_hardness = models.CharField(max_length=255)
    luster = models.CharField(max_length=255)
    streak = models.CharField(max_length=255)
    diaphaneity = models.CharField(max_length=255)
    optical_properties = models.CharField(max_length=255)
    refractive_index = models.CharField(max_length=755)
    crystal_habit = models.CharField(max_length=255)
    specific_gravity = models.CharField(max_length=255)
    group = models.CharField(max_length=255)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name

    # Using .get instead of directly calling the dictionary value
    # in case a key for a rock is not available and that raises a key error
    # here we just provide an empty string to the database
    @classmethod
    def add_minerals_to_database(cls):
        """Method to load initial mineral data from json file"""
        with open('minerals.json', encoding='utf-8', mode='r') as file:
            minerals = json.load(file)
            for mineral in minerals:
                Mineral(
                    name=mineral.get('name'),
                    image_filename=mineral.get('image filename', ''),
                    image_caption=mineral.get('image caption', ''),
                    category=mineral.get('category', ''),
                    formula=mineral.get('formula', ''),
                    strunz_classification=mineral.get('strunz classification', ''),
                    crystal_system=mineral.get('crystal system', ''),
                    unit_cell=mineral.get('unit cell', ''),
                    color=mineral.get('color', ''),
                    crystal_symmetry=mineral.get('crystal symmetry', ''),
                    cleavage=mineral.get('cleavage', ''),
                    mohs_scale_hardness=mineral.get('mohs scale hardness', ''),
                    luster=mineral.get('luster', ''),
                    streak=mineral.get('streak', ''),
                    diaphaneity=mineral.get('diaphaneity', ''),
                    optical_properties=mineral.get('optical properties', ''),
                    refractive_index=mineral.get('refractive index', ''),
                    crystal_habit=mineral.get('crystal habit', ''),
                    specific_gravity=mineral.get('specific gravity', ''),
                    group=mineral.get('group', ''),
                ).save()

minerals/views.py
from django.shortcuts import get_object_or_404, render
from .models import Mineral
import random


# Details view for each mineral, pk is the primary key
def mineral_detail(request, pk):
    """Mineral 'detail' view to display mineral details"""
    mineral = get_object_or_404(Mineral, pk=pk)
    minerals = Mineral.objects.all()
    # create a random mineral variable to pass the template
    random_mineral = random.choice(minerals)

    return render(request, 'minerals/mineral_detail.html', {'mineral': mineral,
                                                            'random_mineral': random_mineral})

minerals_catalog/views.py
import random

from django.shortcuts import render
from django.db.models import Q


from minerals.models import Mineral

m = Mineral.objects.all()


def index(request):
    """Landing 'home' page view to display list of all mineral names"""
    minerals = m
    random_mineral = random.choice(m)

    return render(request, 'index.html', {'minerals': minerals, 'random_mineral': random_mineral})


# Lists minerals for a selected letter search
def mineral_letter(request, letter):
    minerals = m.filter(name__istartswith=letter.lower())
    random_mineral = random.choice(m)

    return render(request, 'index.html', {'minerals': minerals,
                                          'active_letter': letter,
                                          'random_mineral': random_mineral})


# Text Search minerals by name and other mineral categories
def mineral_search(request):
    term = request.GET.get("q")
    minerals = m.filter(
       Q(name__icontains=term) |
        Q(group__icontains=term) |
        Q(image_caption__icontains=term) |
        Q(category__icontains=term) |
        Q(formula__icontains=term) |
        Q(crystal_system__icontains=term) |
        Q(color__icontains=term) |
        Q(luster__icontains=term) |
        Q(crystal_habit__icontains=term) |
        Q(specific_gravity__icontains=term) |
        Q(streak__icontains=term) |
        Q(strunz_classification__icontains=term)
    )
    random_mineral = random.choice(m)

    return render(request, 'index.html', {'minerals': minerals,
                                          'random_mineral': random_mineral})


# Search by mineral group
def mineral_group(request, group):
    random_mineral = random.choice(m)

    minerals = m.filter(group__icontains=group)
    return render(request, 'index.html', {'minerals': minerals,
                                          'random_mineral': random_mineral})


# Search by mineral color
def mineral_color(request, color):
    random_mineral = random.choice(m)

    minerals = m.filter(color__icontains=color)
    return render(request, 'index.html', {'minerals': minerals,
                                          'random_mineral': random_mineral})

minerals/templates/minerals/color_nav.html
{% for color in colors %}
    <ul style="list-style-type: none;">
    <li><a href="{% url 'color' color=color %}">{{ color }}</a></li>
    </ul>
{% endfor %}

minerals/templates/minerals/group_nav.html
{% for group in groups %}
    <ul style="list-style-type: none;">
    <li><a href="{% url 'group' group=group %}">{{ group }}</a></li>
    </ul>
{% endfor %}

minerals/templates/minerals/mineral_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} {{ block.super }}|{{ mineral.name }} {% endblock %}


{% block content %}

    <div class="grid-100 mineral__container">
      <h1 class="mineral__name">{{ mineral.name|title }}</h1>
      <div class="mineral__image-bg">
        <img class="mineral__image" src="{% static 'images' %}/{{ mineral.name }}.jpg" alt="{{ mineral.name|title }}">
        <p class="mineral__caption">{{ mineral.image_caption|title }}</p>
      </div>

<div class="mineral__table-container">

        <table class="mineral__table">
          <tr>
            <td class="mineral__category">Category</td>
            <td>{{ mineral.category|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Formula</td>
            <td class="mineral__formula">{{ mineral.formula|safe }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Strunz Classification</td>
            <td>{{ mineral.strunz_classification|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Unit Cell</td>
            <td>{{ mineral.unit_cell }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Color</td>
            <td>{{ mineral.color|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Crystal Habit</td>
            <td>{{ mineral.crystal_habit|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Mohs Scale Hardness</td>
            <td>{{ mineral.mohs_scale_hardness }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Group</td>
            <td>{{ mineral.group|title }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Specific Gravity</td>
            <td>{{ mineral.specific_gravity|title }}</td>
          </tr>
        </table>
      </div>
    </div>
{% endblock %}

{% block random %}
     <div class="minerals__random">
    <a class="minerals__anchor" href="{% url 'minerals:detail' pk=random_mineral.pk  %}">Show random mineral</a>
  </div>
{% endblock %}

minerals/templates/minerals/mineral_group_nav.html
{% load static from staticfiles %}

<p><i>Fun Fact: There are {{ groups_count}} mineral group{{groups_count|pluralize}} in this site</i> </p>

templates/index.html
{% extends 'layout.html' %}

{% block content %}
<div class="grid-100">
      <ul class="minerals__container">
          {% for mineral in minerals %}
              <li class="minerals__item">
                  <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk  %}">{{ mineral.name }}</a>
              </li>
          {% empty %}
              <li>No minerals for your selected search</li>
          {% endfor %}

      </ul>
</div>
{% endblock %}

{% block random %}
     <div class="minerals__random">
    <a class="minerals__anchor" href="{% url 'minerals:detail' pk=random_mineral.pk  %}">Show random mineral</a>
  </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
{% load mineral_extras %}



<!DOCTYPE html>
<div lang="en">
<head>
  <meta charset="utf-8">
    <title>Mackey's Minerals: A magnificant catalog of minerals {% block title %}{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<section>
  <div class="bounds">
    <div class="grid-100">
      <a href="/">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Macky's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
    </div>
        <h2>Search Minerals Database</h2>
        <form action="{% url 'search' %}" method="GET">
            <ul class="menu">
                <li><input type="search" name="q"></li>
                <li><input type="submit" value="Search" class="button"></li>
            </ul>
        </form>

  <div>
      <h2>Filter Minerals by Letter</h2>
      {% for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}
          {% if letter == active_letter %}
          <a href="{% url 'letter' letter=letter %}" style="font-weight:bolder; font-size:larger">{{ letter }}</a>
          {% else %}
          <a href="{% url 'letter' letter=letter %}">{{ letter }}</a>
          {% endif %}
      {% endfor %}

  </div>
  <br>

  <div class="grid-parent">

    <div class="grid-25" >
        <h2 >Filter By Category </h2>
        {% nav_mineral_groups %}
        <br>
        <h2 >Filter By Color </h2>
        {% nav_mineral_colors %}
    </div>

    <div class="grid-75">
        {% block content %}{% endblock %}
        {% nav_group_list %}
    </div>

  </div>

  </div>
</section>

  {% block random %}{% endblock %}

</body>
</div>
</html>